

--sys계정
-- **계정생성 <- 관리자계정(sys 관리자 계정)
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
--DROP USER finalPractice;

-- 계정 생성
CREATE USER test
IDENTIFIED BY "test1234";

-- 권한 부여 (CREATE위함)
GRANT CONNECT, RESOURCE, CREATE VIEW TO test;

-- 객체 생성 공간 할당 (INSERT위함)
ALTER USER test 
DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM;


--------------------------------------------------------------------------------

DROP TABLE WORK;
DROP SEQUENCE SEQ_WORK_NO;


CREATE TABLE WORK (
    WORK_NO NUMBER PRIMARY KEY,
    PARENT_NO NUMBER
);
--DROP TABLE WORK;

CREATE SEQUENCE SEQ_WORK_NO NOCACHE;



COMMIT;



SELECT * FROM WORK 
WHERE PARENT_NO IS NULL;

SELECT WORK_NO FROM WORK 
WHERE PARENT_NO IS NULL;

SELECT WORK_NO FROM WORK 
WHERE PARENT_NO = 
(
SELECT WORK_NO FROM WORK 
WHERE PARENT_NO IS NULL
)
;

SELECT WORK_NO FROM WORK 
WHERE PARENT_NO = (
    SELECT WORK_NO FROM WORK 
    WHERE PARENT_NO = 
    (
        SELECT WORK_NO FROM WORK 
        WHERE PARENT_NO IS NULL
    )
)
;

SELECT WORK_NO FROM WORK 
WHERE PARENT_NO = (
    SELECT WORK_NO FROM WORK 
    WHERE PARENT_NO = (
        SELECT WORK_NO FROM WORK 
        WHERE PARENT_NO = 
        (
            SELECT WORK_NO FROM WORK 
            WHERE PARENT_NO IS NULL
        )
    )
)
;


SELECT WORK_NO FROM WORK 
WHERE PARENT_NO = (
    SELECT WORK_NO FROM WORK 
    WHERE PARENT_NO = (
        SELECT WORK_NO FROM WORK 
        WHERE PARENT_NO = (
            SELECT WORK_NO FROM WORK 
            WHERE PARENT_NO = 
            (
                SELECT WORK_NO FROM WORK 
                WHERE PARENT_NO IS NULL
            )
        )
    )
)
;

SELECT WORK_NO FROM WORK 
WHERE PARENT_NO = (
    SELECT WORK_NO FROM WORK 
    WHERE PARENT_NO = (
        SELECT WORK_NO FROM WORK 
        WHERE PARENT_NO = (
            SELECT WORK_NO FROM WORK 
            WHERE PARENT_NO = (
                SELECT WORK_NO FROM WORK 
                WHERE PARENT_NO = 
                (
                    SELECT WORK_NO FROM WORK 
                    WHERE PARENT_NO IS NULL
                )
            )
        )
    )
)
;

SELECT WORK_NO FROM WORK 
WHERE PARENT_NO = (
    SELECT WORK_NO FROM WORK 
    WHERE PARENT_NO = (
        SELECT WORK_NO FROM WORK 
        WHERE PARENT_NO = (
            SELECT WORK_NO FROM WORK 
            WHERE PARENT_NO = (
                SELECT WORK_NO FROM WORK 
                WHERE PARENT_NO = (
                    SELECT WORK_NO FROM WORK 
                    WHERE PARENT_NO = 
                    (
                        SELECT WORK_NO FROM WORK 
                        WHERE PARENT_NO IS NULL
                    )
                )
            )
        )
    )
)
;





--NULL경우
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, NULL); --1
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 1);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 2);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 3);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 4);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 5); --6

INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, NULL); --7
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 7);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 8);

INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, NULL);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, NULL);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 10);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 11);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 10);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 11);

INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 2);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 3);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 3);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 2);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 2);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 17);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 18);


COMMIT;


--0경우
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 0); --1
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 1);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 2);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 3);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 4);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 5); --6

INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 0); --7
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 7);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 8);

INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 0);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 0);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 10);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 11);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 10);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 11);

INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 2);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 3);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 3);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 2);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 2);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 17);
INSERT INTO WORK VALUES(SEQ_WORK_NO.NEXTVAL, 18);


COMMIT;



SELECT * FROM WORK;

--NULL경우
SELECT 
    LPAD(' ', LEVEL * 2) || WORK_NO , 
    WORK_NO,
    PARENT_NO
FROM 
    WORK
START WITH PARENT_NO IS NULL 
CONNECT BY PRIOR WORK_NO = PARENT_NO 
--ORDER SIBLINGS BY created_at
;

--SELECT 
--    LPAD(' ', LEVEL * 2, WORK_NO) , 
--    WORK_NO,
--    PARENT_NO
--FROM 
--    WORK
--START WITH PARENT_NO IS NULL 
--CONNECT BY PRIOR WORK_NO = PARENT_NO 
----ORDER SIBLINGS BY created_at
--;

SELECT 
    LPAD(WORK_NO, LEVEL * 2, ' ') , 
    WORK_NO,
    PARENT_NO
FROM 
    WORK
START WITH PARENT_NO IS NULL 
CONNECT BY PRIOR WORK_NO = PARENT_NO 
--ORDER SIBLINGS BY created_at
;

SELECT 
    LPAD(WORK_NO, LEVEL * 2, ' ') , 
    WORK_NO,
    PARENT_NO,
    LEVEL
FROM 
    WORK
START WITH PARENT_NO IS NULL 
CONNECT BY PRIOR WORK_NO = PARENT_NO 
--ORDER SIBLINGS BY created_at
;


--0경우
SELECT 
    LPAD(WORK_NO, LEVEL * 2, ' ') , 
    WORK_NO,
    PARENT_NO,
    LEVEL
FROM 
    WORK
START WITH PARENT_NO=0 
CONNECT BY PRIOR WORK_NO = PARENT_NO 
--ORDER SIBLINGS BY created_at
;


