-- 테이블 삭제
DROP TABLE "USER_PROJECT" CASCADE CONSTRAINTS;
DROP TABLE "PROJECT" CASCADE CONSTRAINTS;
DROP TABLE "USER" CASCADE CONSTRAINTS;
DROP TABLE "AUTH_KEY" CASCADE CONSTRAINTS;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_USER_NO;
DROP SEQUENCE SEQ_PROJECT_NO;
DROP SEQUENCE SEQ_AUTH_KEY_NO;

-- USER 테이블 생성
CREATE TABLE "USER" (
    "USER_NO"      NUMBER            NOT NULL,
    "USER_EMAIL"   VARCHAR2(100)     NOT NULL,
    "USER_PW"      VARCHAR2(100)     NOT NULL,
    "USER_NAME"    VARCHAR2(60)      NOT NULL,
    "USER_PHONE"   VARCHAR2(11)      NULL,  -- 전화번호 NULL 허용
    "USER_ADDR"    VARCHAR2(1000)    NULL,  -- 주소 NULL 허용
    "PROFILE_IMG"  VARCHAR2(1000)    NULL,  -- 프로필 이미지 NULL 허용
    "ENROLL_DATE"  DATE              DEFAULT SYSDATE NULL,
    "ROLE"         CHAR              DEFAULT 'U' NOT NULL,
    "USER_DEL_FL"  CHAR              DEFAULT 'N' NOT NULL,  -- 탈퇴 여부 컬럼 추가
    CONSTRAINT "PK_USER" PRIMARY KEY ("USER_NO"),
    CONSTRAINT "CHK_USER_ROLE" CHECK ("ROLE" IN ('S', 'A', 'U')),  -- ROLE 제약 조건
    CONSTRAINT "CHK_USER_DEL_FL" CHECK ("USER_DEL_FL" IN ('Y', 'N'))  
);

-- 컬럼에 대한 주석 추가
COMMENT ON COLUMN "USER"."USER_NO" IS '사용자 번호';
COMMENT ON COLUMN "USER"."USER_EMAIL" IS '이메일';
COMMENT ON COLUMN "USER"."USER_PW" IS '비밀번호';
COMMENT ON COLUMN "USER"."USER_NAME" IS '이름';
COMMENT ON COLUMN "USER"."USER_PHONE" IS '전화번호';
COMMENT ON COLUMN "USER"."USER_ADDR" IS '주소';
COMMENT ON COLUMN "USER"."PROFILE_IMG" IS '프로필 이미지';
COMMENT ON COLUMN "USER"."ENROLL_DATE" IS '가입일';
COMMENT ON COLUMN "USER"."ROLE" IS '역할';
COMMENT ON COLUMN "USER"."USER_DEL_FL" IS '탈퇴 여부';

-- PROJECT 테이블 생성
CREATE TABLE "PROJECT" (
    "PROJECT_NO"   NUMBER            NOT NULL,
    "PROJECT_TITLE" VARCHAR2(100)     NOT NULL,
    "PROJECT_INFO" VARCHAR2(100)     NOT NULL,
    "CREATE_DATE" DATE  DEFAULT SYSDATE   NOT NULL,
    "MANAGER"      NUMBER            NOT NULL
    
    
);

-- 컬럼에 대한 주석 추가
COMMENT ON COLUMN "PROJECT"."PROJECT_NO" IS '프로젝트 번호';
COMMENT ON COLUMN "PROJECT"."PROJECT_TITLE" IS '프로젝트명';
COMMENT ON COLUMN "PROJECT"."PROJECT_INFO" IS '프로젝트 설명';
COMMENT ON COLUMN "PROJECT"."CREATE_DATE" IS '프로젝트 생성일';
COMMENT ON COLUMN "PROJECT"."MANAGER" IS '프로젝트 매니저';

-- 기본 키 제약 조건 추가
ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY ("PROJECT_NO");

-- USER_PROJECT 테이블 생성
CREATE TABLE "USER_PROJECT" (
    "USER_NO"      NUMBER            NOT NULL,
    "PROJECT_NO"   NUMBER            NOT NULL,
    
    CONSTRAINT FK_USER FOREIGN KEY (USER_NO) REFERENCES "USER" (USER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_PROJECT FOREIGN KEY (PROJECT_NO) REFERENCES "PROJECT" (PROJECT_NO) ON DELETE CASCADE

);

-- 컬럼에 대한 주석 추가
COMMENT ON COLUMN "USER_PROJECT"."USER_NO" IS '사용자 번호';
COMMENT ON COLUMN "USER_PROJECT"."PROJECT_NO" IS '프로젝트 번호';



--이메일 인증키 테이블

CREATE TABLE "AUTH_KEY" (
   "AUTH_KEY_NO"   NUMBER      NOT NULL,
   "CODE"   CHAR(6)      NOT NULL,
   "EMAIL"   VARCHAR2(50)      NOT NULL,
   "CREATE_TIME"   DATE   DEFAULT SYSDATE   NOT NULL
);



COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_NO" IS '인증키 구분 번호(SEQ_AUTH_KEY_NO)';

COMMENT ON COLUMN "AUTH_KEY"."CODE" IS '코드';

COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '이메일';

COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증 코드 생성 시간';

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
   "AUTH_KEY_NO"
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;
CREATE SEQUENCE SEQ_PROJECT_NO NOCACHE;
CREATE SEQUENCE SEQ_AUTH_KEY_NO NOCACHE;

--------------------------------------------------------------------------------
--Work
CREATE TABLE "WORK" (
	"WORK_NO"	    NUMBER		                        NOT NULL,
	"WORK_TITLE"	VARCHAR2(150)	DEFAULT '제목'	    NULL,
	"WORK_CONTENT"	VARCHAR2(4000)	DEFAULT '내용'	    NULL,
	"CREATE_DT"	    DATE	        DEFAULT SYSDATE 	NOT NULL,
	"UPDATE_DT"	    DATE	        DEFAULT NULL	    NULL,
	"DUE_DT"	    DATE	        DEFAULT SYSDATE	    NULL,
	"WORK_ST"	    NUMBER(1)	    DEFAULT 1	        NOT NULL,
	"WORK_PR_ST"	NUMBER(1)	    DEFAULT 0	        NOT NULL,
	"WORK_PR"	    NUMBER(1)	    DEFAULT 0	        NULL,
	"WORK_MN_NO"	NUMBER	        DEFAULT NULL	    NULL,
	"PARENT_NO"	    NUMBER	        DEFAULT NULL	    NULL,
	"PROJECT_NO"	NUMBER		                        NOT NULL
); 

COMMENT ON COLUMN "WORK"."WORK_NO" IS '작업번호(시퀀스)';
COMMENT ON COLUMN "WORK"."WORK_TITLE" IS '작업제목';
COMMENT ON COLUMN "WORK"."WORK_CONTENT" IS '작업내용';
COMMENT ON COLUMN "WORK"."CREATE_DT" IS '작업작성일';
COMMENT ON COLUMN "WORK"."UPDATE_DT" IS '작업수정일(최종)';
COMMENT ON COLUMN "WORK"."DUE_DT" IS '작업마감일';
COMMENT ON COLUMN "WORK"."WORK_ST" IS '삭제0 / 기본 N1';
COMMENT ON COLUMN "WORK"."WORK_PR_ST" IS '0=시작전 / 1=진행중 / 2=완료후';
COMMENT ON COLUMN "WORK"."WORK_PR" IS '0=낮음 / 1=중간 /  2=높음';
COMMENT ON COLUMN "WORK"."WORK_MN_NO" IS '작업자번호(사용자지정)';
COMMENT ON COLUMN "WORK"."PARENT_NO" IS '상위';
COMMENT ON COLUMN "WORK"."PROJECT_NO" IS '프로젝트 번호';
